/* =====================================================
   JARVIS - ASA: DEPLOYMENT
   Every path here does a real thing:
   - ZIP export builds a real .zip and downloads it
   - Save to folder writes real files via the File System
     Access API (same mechanism used in Project Manager)
   - GitHub push makes real GitHub REST API calls using a
     token YOU provide, stored only in this browser's
     localStorage. It never leaves your machine except in
     direct calls to api.github.com.
   Nothing here pretends to provision cloud infrastructure,
   flash firmware, or run CI/CD — those need a real backend
   with actual credentials/toolchains this app doesn't have.
===================================================== */

const GITHUB_TOKEN_KEY = "jarvis_asa_github_token";

let jszipLoadPromise = null;

/* =====================================================
   ZIP EXPORT
===================================================== */

export async function exportAsZip(projectName, files) {

    await ensureJSZip();

    const zip = new window.JSZip();

    files.forEach(file => {
        zip.file(file.path, file.content ?? "");
    });

    const blob = await zip.generateAsync({ type: "blob" });

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");

    a.href = url;
    a.download = `${slugify(projectName)}.zip`;
    a.click();

    URL.revokeObjectURL(url);

    return { deployed: true, target: "zip", detail: `${a.download} downloaded` };
}

function ensureJSZip() {

    if (window.JSZip) return Promise.resolve();

    if (jszipLoadPromise) return jszipLoadPromise;

    jszipLoadPromise = new Promise((resolve, reject) => {

        const script = document.createElement("script");
        script.src = "https://raw.githubusercontent.com/Stuk/jszip/master/dist/jszip.min.js";
        script.onload = resolve;
        script.onerror = () => reject(new Error("Failed to load JSZip."));

        document.head.appendChild(script);
    });

    return jszipLoadPromise;
}

/* =====================================================
   SAVE TO A REAL FOLDER ON DISK
===================================================== */

export async function saveToFolder(files) {

    if (!window.showDirectoryPicker) {
        throw new Error("Folder save isn't supported in this browser (use Chrome or Edge).");
    }

    const dirHandle = await window.showDirectoryPicker();

    for (const file of files) {

        const parts = file.path.split("/").filter(Boolean);
        const fileName = parts.pop();

        let currentDir = dirHandle;

        for (const part of parts) {
            currentDir = await currentDir.getDirectoryHandle(part, { create: true });
        }

        const fileHandle = await currentDir.getFileHandle(fileName, { create: true });
        const writable = await fileHandle.createWritable();

        await writable.write(file.content ?? "");
        await writable.close();
    }

    return { deployed: true, target: "folder", detail: `${files.length} file(s) written to "${dirHandle.name}"` };
}

/* =====================================================
   GITHUB PUSH (real REST API calls)
===================================================== */

export function getGithubToken() {

    return localStorage.getItem(GITHUB_TOKEN_KEY) || "";
}

export function setGithubToken(token) {

    if (token) {
        localStorage.setItem(GITHUB_TOKEN_KEY, token);
    } else {
        localStorage.removeItem(GITHUB_TOKEN_KEY);
    }
}

export async function pushToGithub(repoName, files, { isPrivate = true } = {}) {

    const token = getGithubToken();

    if (!token) {
        throw new Error("No GitHub token saved. Add a personal access token with 'repo' scope first.");
    }

    const headers = {
        "Authorization": `Bearer ${token}`,
        "Accept": "application/vnd.github+json"
    };

    const userRes = await fetch("https://api.github.com/user", { headers });

    if (!userRes.ok) {
        throw new Error("GitHub token rejected. Check that it's valid and has 'repo' scope.");
    }

    const user = await userRes.json();
    const slug = slugify(repoName);

    // Create the repo (ignore 422 = already exists)
    const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: { ...headers, "Content-Type": "application/json" },
        body: JSON.stringify({
            name: slug,
            private: isPrivate,
            description: `Generated by JARVIS Autonomous Solution Architect`,
            auto_init: true
        })
    });

    if (!createRes.ok && createRes.status !== 422) {

        const detail = await createRes.text().catch(() => "");
        throw new Error(`Could not create repo: ${createRes.status} ${detail}`);
    }

    // Push each file via the Contents API
    for (const file of files) {

        await putFileContents({
            owner: user.login,
            repo: slug,
            path: file.path,
            content: file.content ?? "",
            headers
        });
    }

    return {
        deployed: true,
        target: "github",
        detail: `Pushed ${files.length} file(s) to https://github.com/${user.login}/${slug}`,
        url: `https://github.com/${user.login}/${slug}`
    };
}

async function putFileContents({ owner, repo, path, content, headers }) {

    const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}`;

    // Check if the file already exists, to include its sha (required to update)
    let sha;

    try {

        const existing = await fetch(apiUrl, { headers });

        if (existing.ok) {
            const data = await existing.json();
            sha = data.sha;
        }

    } catch {
        // file doesn't exist yet — that's fine, sha stays undefined
    }

    const res = await fetch(apiUrl, {
        method: "PUT",
        headers: { ...headers, "Content-Type": "application/json" },
        body: JSON.stringify({
            message: `Add ${path} (JARVIS ASA)`,
            content: base64Encode(content),
            ...(sha ? { sha } : {})
        })
    });

    if (!res.ok) {

        const detail = await res.text().catch(() => "");
        throw new Error(`Failed to push ${path}: ${res.status} ${detail}`);
    }
}

function base64Encode(str) {

    // handles UTF-8 content correctly, not just latin1
    const bytes = new TextEncoder().encode(str);

    let binary = "";
    bytes.forEach(b => binary += String.fromCharCode(b));

    return btoa(binary);
}

function slugify(name) {

    return (name || "asa-project")
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "asa-project";
}
